services:
  490-test:
    #do this 
    # image: ghcr.io/a1icja/checkhen:main
    # OR
    build:
      context: ./checkhen/
      dockerfile: Dockerfile
    container_name: 490-test
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://ds490:ds490-secure-password@db:5432/postgres
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_Zmlyc3QtbWFzdG9kb24tODMuY2xlcmsuYWNjb3VudHMuZGV2JA
      - CLERK_SECRET_KEY=sk_test_TcZPHqalrJHYkJEujzskija8NLh3IpX3bvo9zWoiHR
      - NTFY_TOPIC=checkhen-ds490
    develop:
      watch:
        - action: rebuild
          path: ./checkhen/
    depends_on:
      - db
      - socket
  db:
    image: postgres:13
    container_name: 490-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ds490
      POSTGRES_PASSWORD: ds490-secure-password
      POSTGRES_DB: postgres
  socket:
    # image: ghcr.io/a1icja/socket-server:main
    build:
      context: ./socket-server/
      dockerfile: Dockerfile
    container_name: 490-socket
    ports:
      - "6060:6060"
    environment:
      - PORT=6060
      - DATABASE_URL=postgres://ds490:ds490-secure-password@db:5432/postgres
    develop:
      watch:
        - action: rebuild
          path: ./socket-server/
    depends_on:
      - db
  # grafana:
  #   image: grafana/grafana-oss:latest
  #   container_name: 490-grafana
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #     - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
  #     - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
  #     - ./grafana/dashboards:/var/lib/grafana/dashboards
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=<FILL_ME_IN>
  #     - GF_SECURITY_ADMIN_USER=<FILL_ME_IN>
  #     - GF_USERS_ALLOW_SIGN_UP=<FILL_ME_IN>
  #   depends_on:
  #     - db
volumes:
  pgdata:
  grafana-data: